#!/bin/bash
if [ "$(id -u)" != "0" ]; then
	echo -e '\033[30;41m''Run this script as root''\033[0m'
	#exit
fi

#read -p "Install program? (y/n) " installProgram

userId=1000
user=$(cat /etc/passwd | grep $userId | sed -e 's/^\([a-zA-Z]\+\).*\([0-9]\{4\}\+\).*:\([\/a-zA-Z]\+\):.*/\1 \2 \3/g')


programs=('git')
programs=(${programs[@]} 'openssh-server')
programs=(${programs[@]} 'vim')
programs=(${programs[@]} 'htop')

#lamp-server^
programs=(${programs[@]} 'apache2')
programs=(${programs[@]} 'mysql-server')
programs=(${programs[@]} 'php5')
programs=(${programs[@]} 'php5-cli')
programs=(${programs[@]} 'php5-mysql')
programs=(${programs[@]} 'libapache2-mod-php5')

#nginx php-fpm
programs=(${programs[@]} 'nginx')
programs=(${programs[@]} 'php5-fpm')

#php curl ...
programs=(${programs[@]} 'php5-gd')
programs=(${programs[@]} 'php5-curl')
programs=(${programs[@]} 'php5-geoip')
programs=(${programs[@]} 'php5-mcrypt')




programs=(${programs[@]} 'vim-gnome')
programs=(${programs[@]} 'chromium-browser')
#programs=(${programs[@]} 'pepperflashplugin-nonfree')
#programs=(${programs[@]} 'Libre')
#programs=(${programs[@]} 'gimp')
#programs=(${programs[@]} 'samba')
#programs=(${programs[@]} 'vbox')
programs=(${programs[@]} 'wine')
programs=(${programs[@]} 'network-manager-openvpn')
programs=(${programs[@]} 'xscreensaver')
programs=(${programs[@]} 'sshfs')
programs=(${programs[@]} 'skype')

for program in ${programs[*]}; do
	if [ "$(dpkg -s $program 2>&1 | grep Status)" = '' ]; then
		echo -e '\033[1;42m''Install '$program'\033[0m'
	else
		echo -e '\033[32;47m''Installed '$program'\033[0m'
	fi
done




