#!/bin/bash
if [ "$(id -u)" != "0" ]; then
	echo -e '\033[30;41m''Run this script as root''\033[0m'
	#exit
fi

#read -p "Install program? (y/n) " installProgram

userId=1000
user=$(cat /etc/passwd | grep $userId | sed -e 's/^\([a-zA-Z]\+\).*\([0-9]\{4\}\+\).*:\([\/a-zA-Z]\+\):.*/\1 \2 \3/g')


programs=('git')
programs=(${programs[@]} 'openssh-server')
programs=(${programs[@]} 'sshfs')
programs=(${programs[@]} 'vim')
programs=(${programs[@]} 'htop')
programs=(${programs[@]} 'screen')
programs=(${programs[@]} 'curl')

#lamp-server^
programs=(${programs[@]} 'apache2')
programs=(${programs[@]} 'mysql-server')
programs=(${programs[@]} 'php')
programs=(${programs[@]} 'php-cli')
programs=(${programs[@]} 'php-mysql')
programs=(${programs[@]} 'libapache2-mod-php5')

#nginx php-fpm
programs=(${programs[@]} 'nginx')
programs=(${programs[@]} 'php-fpm')

#php curl ...
programs=(${programs[@]} 'php-gd')
programs=(${programs[@]} 'php-curl')
programs=(${programs[@]} 'php-geoip')
programs=(${programs[@]} 'php-mcrypt')

#php debug
programs=(${programs[@]} 'php-xdebug')
programs=(${programs[@]} 'php-xhprof')




programs=(${programs[@]} 'vim-gnome')
programs=(${programs[@]} 'chromium-browser')
#programs=(${programs[@]} 'pepperflashplugin-nonfree')
programs=(${programs[@]} 'libreoffice')
programs=(${programs[@]} 'gimp')
#programs=(${programs[@]} 'samba')
programs=(${programs[@]} 'wine')
programs=(${programs[@]} 'network-manager-openvpn')
programs=(${programs[@]} 'network-manager-openvpn-gnome')
programs=(${programs[@]} 'xscreensaver')
programs=(${programs[@]} 'smplayer')
programs=(${programs[@]} 'baobab')
programs=(${programs[@]} 'gnome-disk-utility')
programs=(${programs[@]} 'unar')
programs=(${programs[@]} 'openjdk-7-jre')

programs=(${programs[@]} 'virtualbox')
programs=(${programs[@]} 'skype')

for program in ${programs[*]}; do
	if [ "$(dpkg -s $program 2>&1 | grep Status)" = '' ]; then
		echo -e '\033[1;42m''Install '$program'\033[0m'
	else
		echo -e '\033[1;37;47m''Installed '$program'\033[0m'
	fi
done




