#!/bin/bash

COM='find'


DIRS=(\
	'./'\
)

#PATHS=('')
PATHS_NO=('.git/')
PATHS_NO=(${PATHS_NO[@]} '.svn/')
PATHS_NO=(${PATHS_NO[@]} '.idea/')
PATHS_NO=(${PATHS_NO[@]} 'tmp/')
#PATHS_NO=(${PATHS_NO[@]} 'images/')
#PATHS_NO=(${PATHS_NO[@]} 'cache/')
#PATHS_NO=(${PATHS_NO[@]} 'logs/')
#PATHS_NO=(${PATHS_NO[@]} 'tools/db_pma/')

#NAME=('')
NAME_NO=('*.min.js')
#NAME_NO=(${NAME_NO[@]} '*.csv')
#NAME_NO=(${NAME_NO[@]} '*.log')
#NAME_NO=(${NAME_NO[@]} '*.mo')
#NAME_NO=(${NAME_NO[@]} '*.txt')

TYPE='f'

GREP_DEF_PARAMS='--color -n -I -H'

for item in ${DIRS[*]}; do
	COM=$COM' '$item
done

for item in ${NAME_NO[*]}; do
	COM=$COM" ! -name '"${item}"'"
done
for item in ${PATHS_NO[*]}; do
	for dir in ${DIRS[*]}; do
		COM=$COM' ! -path "'$dir$item'*"'
	done
done

if [ "$2" ]; then
	FIND_PARAMS=' '$2
else
	FIND_PARAMS=''
fi

if [ "$3" ]; then
	GREP_PARAMS=' '$3
else
	GREP_PARAMS=''
fi

COM=$COM" -type f$FIND_PARAMS"
COM=$COM" -exec grep $GREP_DEF_PARAMS$GREP_PARAMS '$1' '{}' \;"

echo -e "\033[1;42m"
echo $COM
echo -e "\033[0m"

eval $COM

echo -e ""
