#!/bin/bash

export DISPLAY=:0.0
export DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$(pgrep xfce4-session)/environ|cut -d= -f2-)
notify-send "$1" "$2" $3


#function addslashes {
#	echo $(printf '%q' "$1")
#}
