#!/bin/bash
#fusermount -u $HOME/sshfs

# Получение пароля
#stty -echo
#printf "Password: "
#read PASSWORD
#stty echo
#printf "\n"

FOLDER=`echo -n $1 | sed "s/[@\.\ ]/_/g"`

if [ $2 ]
then
	KEY="-i $2 "
	KEYFS="-o IdentityFile=$2 "
else
	KEY=""
	KEYFS=""
fi

if [ ! -d $HOME/sshfs/$FOLDER ]
then
	FSDIR=$HOME/sshfs/$FOLDER
	mkdir $FSDIR
	sshfs $KEYFS$1:/ $FSDIR

	ssh $KEY$1

	fusermount -u $FSDIR
	if [ ! "$(ls -A $FSDIR)" ]
	then
		rm -r $FSDIR
	fi
else
	ssh $KEY$1
fi
