#!/bin/bash

# Получение пароля
#stty -echo
#printf "Password: "
#read PASSWORD
#stty echo
#printf "\n"

USER=`whoami`


FOLDER=`echo -n $1 | sed "s/[@\.\ ]/_/g"`
SSHFS_DIR=$HOME'/sshfs'

if [ ! -d $SSHFS_DIR ]; then
	mkdir $SSHFS_DIR
fi

# if need use other IdentityKey
if [ $2 ]; then
	KEY="-i $2 "
	KEYFS="-o IdentityFile=$2 "
else
	KEY=""
	KEYFS=""
fi


# Check install program sshfs
if [ ! "$(dpkg -s sshfs 2>&1 | grep Status)" ]; then
	echo 'Need install program:'
	echo 'sudo apt-get install sshfs'
	exit
fi

# Check user group fuse
if [ ! "$(grep $USER /etc/group | grep ^fuse)" ]; then
	echo 'Need add user in group fuse:'
	echo "sudo usermod -a -G fuse $USER"
	exit
fi


if [ ! -d $SSHFS_DIR/$FOLDER ]; then
	FSDIR=$SSHFS_DIR/$FOLDER
	mkdir $FSDIR
	sshfs $KEYFS$1:/ $FSDIR

	ssh $KEY$1

	fusermount -u $FSDIR
	if [ ! "$(ls -A $FSDIR)" ]
	then
		rm -r $FSDIR
	fi
else
	ssh $KEY$1
fi
