#!/bin/bash
maxVol=100

action=$(echo $2 | grep -o '^[-\+]')
actionVol=$(echo $2 | grep -o '[0-9]\+$')

if [ $action = '+' ]; then
	vol=$(pactl list sinks | grep "^Sink #$1" -A15 | grep -o 'Volume: 0: \+[0-9]\{1,3\}' | grep -o '[0-9]\{1,3\}$')
	if [ $(($actionVol+$vol)) -ge $maxVol ]; then
		pactl -- set-sink-volume $1 $maxVol%
	else
		pactl -- set-sink-volume $1 $2%
	fi
else
	pactl -- set-sink-volume $1 $2%
fi
