#!/bin/bash

while : ; do
	case "$1" in
		--)
			shift
			for var in "$@"; do
				if [[ $var =~ [[:space:]] ]] || [[ $var =~ \^ ]] || [[ $var =~ \\ ]]; then
					var=\'"$var"\'
				fi

				if [[ $com ]]; then
					com=$com' '"$var"
				else
					com="$var"
				fi
			done
			break
		;;
		-*)
			name=$(echo $1 | sed -e "s/^-//" )
			if [[ $2 =~ ^- ]]; then
				declare "$name"=true
				shift 1
			else
				var="$2"
				if [[ $var =~ [[:space:]] ]]; then
					var=\'"$var"\'
				fi
				declare "$name"="$var"
				shift 2
			fi

		;;

		*)  # No more options
			for var in "$@"; do
				if [[ $var =~ [[:space:]] ]] || [[ $var =~ \^ ]]; then
					var=\'"$var"\'
				fi

				if [[ $com ]]; then
					com=$com' '"$var"
				else
					com="$var"
				fi
			done
			break
		;;

	esac
done






com=`echo "$com" | sed -e "s/'/'\\\\\\\''/g"`

#echo "com=#$com#"


xtermCom="xterm"
if [[ $h = true ]]; then xtermCom="$xtermCom -hold"; fi
if [[ $m = true ]]; then xtermCom="$xtermCom -maximized"; fi
if [[ $g ]]; then        xtermCom="$xtermCom -geometry $g"; fi

xtermCom="$xtermCom -xrm 'XTerm*selectToClipboard: true' -sb -rightbar"

if [[ $t ]]; then title="$t"; else title="$com"; fi

if [[ $s ]]; then
	xtermCom="$xtermCom -title 's:$s: $title'"
	com=`echo "$com" | sed -e "s/'/'\\\\\\\''/g"`
	xtermCom="$xtermCom -e /bin/bash -c 'ssh -t $s '\''$com'\'''"
else
	xtermCom="$xtermCom -title '"$title"'"
	xtermCom="$xtermCom -e /bin/bash -c '$com'"
fi




#echo "$xtermCom &"
eval "$xtermCom &"
