#!/bin/bash

cmd=$(echo $1 | sed -e 's/localapp:\/\///g')
cmd=$(echo $cmd | sed -e 's/%20/ /g')

app=$(echo $cmd | sed -e 's/^\([^:]*\):.*/\1/g')
param=$(echo $cmd | sed -e 's/'$app'://g')

$app $param
